name: deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        node-version: ${{ matrix.node-version }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
    - run: npm ci
    - run: npm run build --if-present
